[project]
name = "er-aws-rds"
version = "0.13.0"
description = "ERv2 module for managing AWS rds instances"
authors = [{ name = "AppSRE", email = "sd-app-sre@redhat.com" }]
license = { text = "Apache 2.0" }
readme = "README.md"
requires-python = "~= 3.14.0"
dependencies = [
    "boto3-stubs[ec2,rds]==1.43.61",
    "boto3==1.43.61",
    "external-resources-io==0.7.0",
    "pydantic==2.13.4",
    "semver==3.0.4",
]

[project.urls]
homepage = "https://github.com/app-sre/er-aws-rds"
repository = "https://github.com/app-sre/er-aws-rds"
documentation = "https://github.com/app-sre/er-aws-rds"

[dependency-groups]
dev = [
    # Development dependencies
    "external-resources-io[cli]==0.7.0",
    "mypy==2.3.0",
    "pytest-cov==7.1.0",
    "pytest==9.1.1",
    "ruff==0.16.1",
]

[project.scripts]
generate-tf-config = 'er_aws_rds.config:generate_tf_files'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Ruff configuration
[tool.ruff]
line-length = 88
fix = true

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "CPY",    # Missing copyright header
    "undocumented-public-module",   # Missing docstring in public module
    "undocumented-public-class",
    "undocumented-public-method",
    "undocumented-public-package",   # Missing docstring in public package
    "undocumented-public-init",   # Missing docstring in __init__
    "incorrect-blank-line-before-class",   # 1 blank line required before class docstring
    "blank-line-before-class",   # No blank lines allowed before class docstring
    "multi-line-summary-first-line",   # multi-line-summary-first-line
    "multi-line-summary-second-line",   # multi-line-summary-second-line
    "D4",     # Doc string style
    "line-too-long",   # Line too long
    "logging-f-string",   # Logging statement uses string formatting
    "assert",   # Use of assert detected. Pytest uses assert
    "raw-string-in-exception",
    "f-string-in-exception",
    "raise-vanilla-args",
    # pydoclint
    "DOC",
    # May conflict with the formatter, https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "tab-indentation",
    "indentation-with-invalid-multiple",
    "indentation-with-invalid-multiple-comment",
    "over-indented",
    "docstring-tab-indentation",
    "triple-single-quotes",
    "Q",
    "missing-trailing-comma",
    "prohibited-trailing-comma",
    "single-line-implicit-string-concatenation",
    "commented-out-code",
    "suspicious-subprocess-import",
    "subprocess-without-shell-equals-true",
    "magic-value-comparison",
]
[tool.ruff.format]
preview = true

[tool.ruff.lint.isort]
known-first-party = ["er_aws_rds"]

[tool.ruff.lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel"]
runtime-evaluated-decorators = [
    "pydantic.validate_call",
    "dataclasses.dataclass",
]

# Mypy configuration
[tool.mypy]
files = ["er_aws_rds", "hooks", "tests"]
enable_error_code = ["truthy-bool", "redundant-expr"]
no_implicit_optional = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

# Coverage configuration
[tool.coverage.run]
branch = true
omit = ["*/tests/*"]

[tool.coverage.report]
fail_under = 85
